"""Lab Project Factory — creates GhostMirror projects scoped to lab targets."""

from __future__ import annotations

from pathlib import Path

from ghostmirror.core.config_manager import ConfigManager
from ghostmirror.core.exceptions import ProjectAlreadyExistsError
from ghostmirror.core.project_manager import ProjectHandle, ProjectManager
from ghostmirror.core.scope_manager import ScopeManager
from ghostmirror.models.lab_target import LabTarget
from ghostmirror.models.scope import AllowedTests, ScopeModel, ScopeProjectInfo, ScopeTargets
from ghostmirror.storage.filesystem import FileSystemStorage

LAB_CLIENT = "GhostMirror Lab"
PROJECT_SUBDIRS = (
    "logs",
    "findings",
    "evidence",
    "reports",
    "profiles",
    "execution",
    "benchmarks",
)


class LabProjectFactory:
    """Creates projects specifically for lab environments with safety constraints."""

    def __init__(
        self,
        config: ConfigManager | None = None,
        project_manager: ProjectManager | None = None,
    ) -> None:
        self.config = config or ConfigManager()
        self.config.load()
        self.scope_manager = ScopeManager()
        self.project_manager = project_manager or ProjectManager(
            config=self.config, scope_manager=self.scope_manager
        )

    def create(self, lab: LabTarget) -> ProjectHandle:
        """Create a lab-scoped project and return its handle.

        The project slug follows the pattern ``lab-<lab-id>``.
        """
        slug = f"lab-{lab.id}"
        project_path = self.config.projects_dir / slug

        if project_path.exists():
            raise ProjectAlreadyExistsError(
                f"Lab project {slug!r} already exists at {project_path}. "
                "Remove it or use a different lab."
            )

        # 1. Directory tree
        FileSystemStorage.ensure_dir(project_path)
        for subdir in PROJECT_SUBDIRS:
            FileSystemStorage.ensure_dir(project_path / subdir)

        # 2. Metadata
        from ghostmirror.models.project import ProjectModel

        metadata = ProjectModel(
            name=f"{lab.name} Lab",
            client=LAB_CLIENT,
            domain="localhost",
            notes=f"Lab Mode project for {lab.id}. Auto-generated by GhostMirror Lab Manager.",
        )
        FileSystemStorage.write_json(
            project_path / "metadata.json",
            metadata.model_dump(mode="json"),
        )

        # 3. Scope (lab=true, localhost targets, restrictive tests)
        scope = self._build_lab_scope(lab)
        self.scope_manager.write_scope(project_path / "scope.yaml", scope)

        return ProjectHandle(slug=slug, path=project_path, metadata=metadata)

    @staticmethod
    def _build_lab_scope(lab: LabTarget) -> ScopeModel:
        return ScopeModel(
            project=ScopeProjectInfo(
                client=LAB_CLIENT,
                name=f"{lab.name} Lab",
                lab=True,
            ),
            targets=ScopeTargets(
                domains=[],
                ips=["127.0.0.1"],
                urls=[lab.default_url],
            ),
            allowed_tests=AllowedTests(
                recon=True,
                ssl_scan=False,
                web_scan=True,
                port_scan=True,
                credential_audit=False,
                exploitation=False,
                destructive_tests=False,
            ),
        )

    @staticmethod
    def find_lab_project(
        projects_dir: Path, lab_id: str
    ) -> Path | None:
        """Return the path of an existing lab project for *lab_id*, or None."""
        slug = f"lab-{lab_id}"
        candidate = projects_dir / slug
        if candidate.is_dir() and (candidate / "scope.yaml").exists():
            return candidate
        return None
