"""Parser for raw JSONL output files generated by Nuclei scans."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ghostmirror.core.logger import get_logger
from ghostmirror.models.nuclei_result import NucleiResult

logger = get_logger()


class NucleiParser:
    """Parser to handle Nuclei JSONL (JSON Lines) outputs."""

    @staticmethod
    def parse_line(line: str) -> NucleiResult | None:
        """Parses a single line of raw Nuclei JSONL output.

        Parameters
        ----------
        line : str
            JSON line string.

        Returns
        -------
        NucleiResult | None
            Parsed result object or None if invalid.
        """
        line_clean = line.strip()
        if not line_clean:
            return None

        try:
            data = json.loads(line_clean)
        except json.JSONDecodeError as exc:
            logger.warning("NUCLEI_JSON_LINE_INVALID line={} error={}", line_clean[:100], exc)
            return None

        # Build fields for NucleiResult
        try:
            info = data.get("info") or {}
            
            # Map classifications
            classification = info.get("classification") or {}
            cve_val = classification.get("cve-id")
            if not cve_val and isinstance(classification.get("cve"), list):
                cves = classification.get("cve")
                if cves:
                    cve_val = cves[0]
            elif not cve_val and isinstance(classification.get("cve"), str):
                cve_val = classification.get("cve")

            cvss_val = info.get("cvss-score") or classification.get("cvss-score")
            if cvss_val is None:
                # Fallback to general classification list
                cvss_val = classification.get("cvss-score")

            result_dict = {
                "template-id": data.get("template-id"),
                "template_name": info.get("name") or data.get("template-id"),
                "severity": info.get("severity") or "info",
                "matched-at": data.get("matched-at") or data.get("host"),
                "host": data.get("host"),
                "ip": data.get("ip"),
                "curl-command": data.get("curl-command"),
                "reference": info.get("reference") or [],
                "description": info.get("description"),
                "tags": info.get("tags") or [],
                "cve": cve_val,
                "cvss": float(cvss_val) if cvss_val is not None else None,
                "matcher-name": data.get("matcher-name"),
                "timestamp": data.get("timestamp") or "",
            }

            return NucleiResult.model_validate(result_dict)

        except Exception as exc:
            logger.error("NUCLEI_RESULT_MAPPING_FAILED error={} data={}", exc, data)
            return None

    @classmethod
    def parse_file(cls, filepath: Path | str) -> list[NucleiResult]:
        """Reads and parses an entire JSONL output file.

        Parameters
        ----------
        filepath : Path | str
            Filepath to read.

        Returns
        -------
        list[NucleiResult]
            List of parsed scan results.
        """
        path = Path(filepath)
        results: list[NucleiResult] = []

        if not path.exists():
            logger.warning("NUCLEI_OUTPUT_FILE_MISSING path={}", path)
            return results

        try:
            with open(path, "r", encoding="utf-8") as f:
                for line in f:
                    parsed = cls.parse_line(line)
                    if parsed:
                        results.append(parsed)
        except Exception as exc:
            logger.error("NUCLEI_FILE_READ_FAILED path={} error={}", path, exc)
            raise ValueError(f"Failed to read Nuclei output file {path}: {exc}") from exc

        return results
