"""Pydantic models for vulnerability findings and standardized scan results."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any
from pydantic import BaseModel, Field



class FindingSeverity(str, Enum):
    """Vulnerability severity levels matching Sprint 2 requirements."""

    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


def _utcnow() -> datetime:
    """Timezone-aware UTC timestamp."""
    return datetime.now(timezone.utc)


class FindingModel(BaseModel):
    """Represents a single detected security issue or audit observation."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    title: str = Field(..., min_length=1, description="Short summary of the finding")
    description: str = Field(..., min_length=1, description="Detailed analysis of the issue")
    severity: FindingSeverity = Field(..., description="Vulnerability severity level")
    target: str = Field(..., description="Target scanned when this finding was identified")
    evidence: str | None = Field(default=None, description="Request/response snippets or other evidence")
    recommendation: str = Field(..., min_length=1, description="Remediation instructions")
    category: str | None = Field(default=None, description="Finding category (e.g. Vulnerability Intelligence)")
    cvss: float | None = Field(default=None, ge=0, le=10, description="CVSS score")
    epss: float | None = Field(default=None, ge=0, le=1, description="EPSS probability score")
    kev: bool | None = Field(default=None, description="Whether CVE is in CISA KEV catalog")
    impact: str | None = Field(default=None, description="Impact level (HIGH, MEDIUM, LOW)")
    probability: str | None = Field(default=None, description="Exploitation probability (HIGH, MEDIUM, LOW)")
    exploitability: str | None = Field(default=None, description="Weaponization level")
    priority: int | None = Field(default=None, description="Priority rank (1 = highest)")
    references: list[str] | None = Field(default=None, description="Reference URLs")
    created_at: datetime = Field(default_factory=_utcnow, description="Timestamp when the finding was recorded")


class ScanResultModel(BaseModel):
    """Standardized output schema for all scanners."""

    scanner_name: str = Field(..., description="Name of the executing scanner")
    target: str = Field(..., description="Scan target domain or IP")
    started_at: datetime = Field(..., description="Timestamp of when the scan started")
    finished_at: datetime = Field(..., description="Timestamp of when the scan finished")
    status: str = Field(..., description="Status of the scan (e.g. completed, failed)")
    findings: list[FindingModel] = Field(default_factory=list, description="List of findings generated by the scan")
    statistics: dict[str, int] = Field(default_factory=dict, description="Scan statistics like severity counts")
    certificate_summary: dict[str, Any] | None = Field(default=None, description="SSL/TLS certificate summary for SSL scans")
    open_ports: list[int] | None = Field(default=None, description="List of open ports found during scanning")
    services: list[str] | None = Field(default=None, description="List of service names discovered during scanning")

